database:
  #mysqldsn: OMEGA3:OMEGA#@tcp(hiffu.maribel:1314)/OMEGA3?charset=utf8mb4&parseTime=True&loc=Local


server:
  port: 27015

IoTDB:
  #host: "your host"
  #port: 11451
  #username: usami
  #password: renko
  queryTimeoutMs: 4000
  pool:

    maxConnections: 5
    timeout: 60000
    fetchMetadataAuto: false


